/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type Pattern2OverridesProps = {
    Pattern2?: PrimitiveOverrideProps<FlexProps>;
    "Frame 154"?: PrimitiveOverrideProps<FlexProps>;
    Vector44379?: PrimitiveOverrideProps<IconProps>;
    Vector44380?: PrimitiveOverrideProps<IconProps>;
    Vector44381?: PrimitiveOverrideProps<IconProps>;
    Vector44382?: PrimitiveOverrideProps<IconProps>;
    Vector44383?: PrimitiveOverrideProps<IconProps>;
    Vector44384?: PrimitiveOverrideProps<IconProps>;
    Vector44385?: PrimitiveOverrideProps<IconProps>;
    Vector44386?: PrimitiveOverrideProps<IconProps>;
    Vector44387?: PrimitiveOverrideProps<IconProps>;
    Vector44388?: PrimitiveOverrideProps<IconProps>;
    "Frame 155"?: PrimitiveOverrideProps<FlexProps>;
    Vector44390?: PrimitiveOverrideProps<IconProps>;
    Vector44391?: PrimitiveOverrideProps<IconProps>;
    Vector44392?: PrimitiveOverrideProps<IconProps>;
    Vector44393?: PrimitiveOverrideProps<IconProps>;
    Vector44394?: PrimitiveOverrideProps<IconProps>;
    Vector44395?: PrimitiveOverrideProps<IconProps>;
    Vector44396?: PrimitiveOverrideProps<IconProps>;
    Vector44397?: PrimitiveOverrideProps<IconProps>;
    Vector44398?: PrimitiveOverrideProps<IconProps>;
    Vector44399?: PrimitiveOverrideProps<IconProps>;
    "Frame 156"?: PrimitiveOverrideProps<FlexProps>;
    Vector44401?: PrimitiveOverrideProps<IconProps>;
    Vector44402?: PrimitiveOverrideProps<IconProps>;
    Vector44403?: PrimitiveOverrideProps<IconProps>;
    Vector44404?: PrimitiveOverrideProps<IconProps>;
    Vector44405?: PrimitiveOverrideProps<IconProps>;
    Vector44406?: PrimitiveOverrideProps<IconProps>;
    Vector44407?: PrimitiveOverrideProps<IconProps>;
    Vector44408?: PrimitiveOverrideProps<IconProps>;
    Vector44409?: PrimitiveOverrideProps<IconProps>;
    Vector44410?: PrimitiveOverrideProps<IconProps>;
    "Frame 157"?: PrimitiveOverrideProps<FlexProps>;
    Vector44412?: PrimitiveOverrideProps<IconProps>;
    Vector44413?: PrimitiveOverrideProps<IconProps>;
    Vector44414?: PrimitiveOverrideProps<IconProps>;
    Vector44415?: PrimitiveOverrideProps<IconProps>;
    Vector44416?: PrimitiveOverrideProps<IconProps>;
    Vector44417?: PrimitiveOverrideProps<IconProps>;
    Vector44418?: PrimitiveOverrideProps<IconProps>;
    Vector44419?: PrimitiveOverrideProps<IconProps>;
    Vector44420?: PrimitiveOverrideProps<IconProps>;
    Vector44421?: PrimitiveOverrideProps<IconProps>;
    "Frame 158"?: PrimitiveOverrideProps<FlexProps>;
    Vector44423?: PrimitiveOverrideProps<IconProps>;
    Vector44424?: PrimitiveOverrideProps<IconProps>;
    Vector44425?: PrimitiveOverrideProps<IconProps>;
    Vector44426?: PrimitiveOverrideProps<IconProps>;
    Vector44427?: PrimitiveOverrideProps<IconProps>;
    Vector44428?: PrimitiveOverrideProps<IconProps>;
    Vector44429?: PrimitiveOverrideProps<IconProps>;
    Vector44430?: PrimitiveOverrideProps<IconProps>;
    Vector44431?: PrimitiveOverrideProps<IconProps>;
    Vector44432?: PrimitiveOverrideProps<IconProps>;
    "Frame 160"?: PrimitiveOverrideProps<FlexProps>;
    Vector44434?: PrimitiveOverrideProps<IconProps>;
    Vector44435?: PrimitiveOverrideProps<IconProps>;
    Vector44436?: PrimitiveOverrideProps<IconProps>;
    Vector44437?: PrimitiveOverrideProps<IconProps>;
    Vector44438?: PrimitiveOverrideProps<IconProps>;
    Vector44439?: PrimitiveOverrideProps<IconProps>;
    Vector44440?: PrimitiveOverrideProps<IconProps>;
    Vector44441?: PrimitiveOverrideProps<IconProps>;
    Vector44442?: PrimitiveOverrideProps<IconProps>;
    Vector44443?: PrimitiveOverrideProps<IconProps>;
    "Frame 161"?: PrimitiveOverrideProps<FlexProps>;
    Vector44445?: PrimitiveOverrideProps<IconProps>;
    Vector44446?: PrimitiveOverrideProps<IconProps>;
    Vector44447?: PrimitiveOverrideProps<IconProps>;
    Vector44448?: PrimitiveOverrideProps<IconProps>;
    Vector44449?: PrimitiveOverrideProps<IconProps>;
    Vector44450?: PrimitiveOverrideProps<IconProps>;
    Vector44451?: PrimitiveOverrideProps<IconProps>;
    Vector44452?: PrimitiveOverrideProps<IconProps>;
    Vector44453?: PrimitiveOverrideProps<IconProps>;
    Vector44454?: PrimitiveOverrideProps<IconProps>;
    "Frame 162"?: PrimitiveOverrideProps<FlexProps>;
    Vector44456?: PrimitiveOverrideProps<IconProps>;
    Vector44457?: PrimitiveOverrideProps<IconProps>;
    Vector44458?: PrimitiveOverrideProps<IconProps>;
    Vector44459?: PrimitiveOverrideProps<IconProps>;
    Vector44460?: PrimitiveOverrideProps<IconProps>;
    Vector44461?: PrimitiveOverrideProps<IconProps>;
    Vector44462?: PrimitiveOverrideProps<IconProps>;
    Vector44463?: PrimitiveOverrideProps<IconProps>;
    Vector44464?: PrimitiveOverrideProps<IconProps>;
    Vector44465?: PrimitiveOverrideProps<IconProps>;
    "Frame 163"?: PrimitiveOverrideProps<FlexProps>;
    Vector44467?: PrimitiveOverrideProps<IconProps>;
    Vector44468?: PrimitiveOverrideProps<IconProps>;
    Vector44469?: PrimitiveOverrideProps<IconProps>;
    Vector44470?: PrimitiveOverrideProps<IconProps>;
    Vector44471?: PrimitiveOverrideProps<IconProps>;
    Vector44472?: PrimitiveOverrideProps<IconProps>;
    Vector44473?: PrimitiveOverrideProps<IconProps>;
    Vector44474?: PrimitiveOverrideProps<IconProps>;
    Vector44475?: PrimitiveOverrideProps<IconProps>;
    Vector44476?: PrimitiveOverrideProps<IconProps>;
    "Frame 159"?: PrimitiveOverrideProps<FlexProps>;
    Vector44478?: PrimitiveOverrideProps<IconProps>;
    Vector44479?: PrimitiveOverrideProps<IconProps>;
    Vector44480?: PrimitiveOverrideProps<IconProps>;
    Vector44481?: PrimitiveOverrideProps<IconProps>;
    Vector44482?: PrimitiveOverrideProps<IconProps>;
    Vector44483?: PrimitiveOverrideProps<IconProps>;
    Vector44484?: PrimitiveOverrideProps<IconProps>;
    Vector44485?: PrimitiveOverrideProps<IconProps>;
    Vector44486?: PrimitiveOverrideProps<IconProps>;
    Vector44487?: PrimitiveOverrideProps<IconProps>;
} & EscapeHatchProps;
export declare type Pattern2Props = React.PropsWithChildren<Partial<FlexProps> & {
    overrides?: Pattern2OverridesProps | undefined | null;
}>;
export default function Pattern2(props: Pattern2Props): React.ReactElement;
